<h1>A 404 error occurred</h1>
<h2>{{ message }}</h2>

{% if reason is not empty %}
    {% if reason == constant('Zend\\Mvc\\Application::ERROR_CONTROLLER_CANNOT_DISPATCH') %}
        The requested controller was unable to dispatch the request.
    {% elseif reason == constant('Zend\\Mvc\\Application::ERROR_MIDDLEWARE_CANNOT_DISPATCH') %}
        The requested middleware was unable to dispatch the request.
    {% elseif reason == constant('Zend\\Mvc\\Application::ERROR_CONTROLLER_NOT_FOUND') %}
        The requested controller could not be mapped to an existing controller class.
    {% elseif reason == constant('Zend\\Mvc\\Application::ERROR_CONTROLLER_INVALID') %}
        The requested controller was not dispatchable.
    {% elseif reason == constant('Zend\\Mvc\\Application::ERROR_ROUTER_NO_MATCH') %}
        The requested URL could not be matched by routing.
    {% else %}
        We cannot determine at this time why a 404 was generated.
    {% endif %}
{% endif %}

{% if controller is not empty %}
    <dl>
        <dt>Controller:</dt>
        <dd>
            {{ controller }}
            {% if controller_class is not empty and controller_class != controller %}
                (resolves to {{ controller_class }})
            {% endif %}
        </dd>
    </dl>

{% endif %}


{% if display_exceptions %}
    {% if exception is defined and ( exception is instanceof('\Throwable') or exception is instanceof('\Exception') ) %}

        <h2>Additional information:</h2>
        <h3> {{ class(exception) }}</h3>
        <dl>
            <dt>File:</dt>
            <dd>
                <pre class="prettyprint linenums">{{ exception.getFile }}:{{ exception.getLine }}</pre>
            </dd>
            <dt>Message:</dt>
            <dd>
                <pre class="prettyprint linenums">{{ exception.getMessage }}</pre>
            </dd>
            <dt>Stack trace:</dt>
            <dd>
                <pre class="prettyprint linenums">{{ exception.getTraceAsString }}</pre>
            </dd>
        </dl>
    {% endif %}

    {% set exception = exception.getPrevious %}
    {% if exception is not null %}
        <hr/>
        <h2>Previous exceptions:</h2>
        <ul class="unstyled">

            {% for i in 0..100 if exception is not null %}
                <li>
                    <h3>{{ class(exception) }}</h3>
                    <dl>
                        <dt>File:</dt>
                        <dd>
                            <pre class="prettyprint linenums">{{ exception.getFile }}:{{ exception.getLine }}</pre>
                        </dd>
                        <dt>Message:</dt>
                        <dd>
                            <pre class="prettyprint linenums">{{ exception.getMessage }}</pre>
                        </dd>
                        <dt>Stack trace:</dt>
                        <dd>
                            <pre class="prettyprint linenums">{{ exception.getTraceAsString }}</pre>
                        </dd>
                    </dl>
                </li>

                {% set exception = exception.getPrevious %}
            {% endfor %}

        </ul>
    {% else %}
        <h3>No Exception available</h3>
    {% endif %}
{% endif %}
